server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*.log

    relabel_configs:
      - source_labels: [__path__]
        regex: '.*/([0-9a-f]{64})/.*\.log'
        target_label: container_id

      - source_labels: [container_id]
        target_label: container_name
        replacement: '${1}' 
